---
controllers:
  shell:
    max_workers: 5
    name_stub: SHELL_WORKER
    queues:
      - bash

logging:
  directory: /log/directory
  pids: /pid/directory
  main_filename: hive.log
  home_directory: /path/to/test/home

timings:
  worker_loop_interval: 5
  controller_loop_interval: 5

network:
  scheduler: https://example.com/scheduler
  cert: /path/to/certificate.pem
  cafile: /path/to/certificate-authorities.pem
