---
controllers:
  shell:
    max_workers: 5
    name_stub: SHELL_WORKER
    queues:
      - bash

logging:
  directory: logs
  pids: pids
  main_filename: hive.log

timings:
  worker_loop_interval: 5

network:
  scheduler: https://example.com/scheduler
  cert: /path/to/certificate.pem
  cafile: /path/to/certificate-authorities.pem
