test:
  daemon_name: HIVE

  controllers:
#    shell:
     android:
      max_workers: 5
      name_stub: ANDROID #SHELL_WORKER
      queues:
        - bash
  
  logging:
    directory: /Users/khana46/opt/logs
    pids: /Users/khana46/opt/pids
    main_filename: hive.log
    main_level: DEBUG
    worker_level: DEBUG
    home: /Users/khana46/opt/home
    homes_to_keep: 5
  
  timings:
    worker_loop_interval: 5
    controller_loop_interval: 5
  
  network:
    scheduler: https://hive.test.cloud.bbc.co.uk/
    devicedb: https://devicedb.test.cloud.bbc.co.uk/
    cert: /opt/certs/user.pem
    cafile: /opt/certs/ca-bundle.pem

  datastore:
    filename: /Users/khana46/opt/datastore.db

  diagnostic:
    android:
      wifi: Connected
      memory: {
          min: 1042,
          max: 1000000,
      }
    ios:
      bluetooth: true