test:
  daemon_name: HIVE

  controllers: 
    android:
      name_stub: ANDROID #SHELL_WORKER
      port_range_size: 10
      queues:
        - bash
  
  ports:
    minimum: 4000
    maximum: 5000

  logging:
    directory: /Users/khana46/opt/logs
    pids: /Users/khana46/opt/pids
    console_level: DEBUG
    main_filename: hive.log
    main_level: DEBUG
    worker_level: DEBUG
    home: /Users/khana46/opt/home
    homes_to_keep: 5
  
  timings:
    worker_loop_interval: 5
    controller_loop_interval: 5
  
  network:
    scheduler: https://hive.test.cloud.bbc.co.uk/
    devicedb: https://devicedb.test.cloud.bbc.co.uk/
    cert: /opt/certs/user.pem
    cafile: /opt/certs/ca-bundle.pem

  datastore:
    filename: /Users/khana46/opt/datastore.db

  # diagnostics:
  #   android: 
  #         uptime:
  #           reboot_timeout: 3000
              
    #     wifi: {
    #         status: Connected,
    #         access_point: TVMP-DevNet,
    #     }
    #     battery: {

    #     }
    #     memory: {
    #       free: 1042,
    #       used: 1000000,
    #     }
    # ios:
    #   parameter : criteria 